name: first action
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu_latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print Good bye
        run: echo "done -bye"
    
